name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CR_IMAGE_NAME: mm404/airprint-mfc9970cdw

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./build.sh $CR_IMAGE_NAME
    # - name: Test container
    #   run: docker run ${{ env.CR_IMAGE_NAME }}:latest --version
    - name: Log in to Docker hub
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_HUB_KEY }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Push image to Docker
      if: github.event_name == 'push'
      run: docker push -a $CR_IMAGE_NAME
